### ISSUE TITLE
Items are hidden with no way of changing that

### ISSUE THREAD

**Issue by MarvinG6547** [Trico-Everfire/p2-publishing-tool#22] opened 2023-02-28 19:49 UTC
So I uploaded a map with the tool and when my friend went to subscribe to the map it told him that the item was hidden.
(v His screenschot v)
![image](https://user-images.githubusercontent.com/117035792/221962928-b15796db-9afe-4f6a-9c32-9ccfbefc9eff.png)
I went to change the visibility but the button was just gone.
![image](https://user-images.githubusercontent.com/117035792/221962589-90ad03de-9673-40bb-9783-27cce26dbef6.png)
I went into the tool and it said that the visibility was set to public but it obviously wasn't.
![image](https://user-images.githubusercontent.com/117035792/221962838-a7380ffa-b2e5-4393-b477-2330387f77e7.png)

**Comment by Trico-Everfire** [comment] 2023-02-28 20:12
I'll look into it.

**Comment by Trico-Everfire** [comment] 2023-03-01 01:28
This issue runs way deeper than I thought, Steam's terrible system is fucking up because I think Poral 2's workshop doesn't like the new API. I am incredibly confused and it's not cooperating.

**Comment by MarvinG6547** [comment] 2023-03-01 14:21
So what now?

**Comment by Trico-Everfire** [comment] 2023-03-01 14:46
now, I'll have to wait, I am attempting to contact a Valve contractor in the hopes they can shed light on the issue, I will try to fix this issue to the best of my abilities, even if I have to take Portal 2's original uploader apart  to fix the issue. This may take a while tho, I am sorry for the inconvenience.

**Comment by Trico-Everfire** [comment] 2023-03-01 14:47
A workaround currently is to create a dummy item with Portal 2's original uploader and editing it with mine, I'll have to snoop around what Portal 2's does differently, but without it's source code I can only guess.

**Comment by MarvinG6547** [comment] 2023-03-01 21:10
Good luck

**Comment by Trico-Everfire** [comment] 2023-03-03 21:44
Should be fixed in next release (in a few minutes.)

**Comment by Trico-Everfire** [comment] 2023-03-03 22:04
https://github.com/Trico-Everfire/p2-publishing-tool/releases/tag/v2.0.6-beta

**Comment by Trico-Everfire** [comment] 2023-03-03 23:35
As soon as someone confirms it works for them, I'll close this issue.

**Comment by Trico-Everfire** [comment] 2023-03-04 16:41
Issue has been confirmed to be fixed in newest release, if this reoccurs reopen issue.

**Closed by Trico-Everfire** 2023-03-04 16:41 UTC
